with global_tenant_history_daily_billing_tbl as (
    select * from {{ ref('global_tenant_history_daily_billing_tbl')}}
)

-- select
--     date_recorded,
--     root,
--     parent_global_id,
--     parent_name,
--     tenant_global_id,
--     tenant_name,
--     registration_date,
--     domain,
--     partner_pricing,
--     plan_id,
--     plan_name,
--     premium_id,
--     premium_name,
--     incident_management,
--     security_awareness_training,
--     simulation_and_training_bundle,
--     simulation_and_training_bundle_plus,
--     ai_empower_bundle,
--     themis_co_pilot,
--     ato,
--     teams_protection,
--     file_scanning,
--     link_scanning,
--     multi_tenancy,
--     licensed_profiles,
--     active_profiles,
--     shared_profiles,
--     trial_plan_id,
--     trial_plan_name,
--     trial_premium_id,
--     trial_premium_name,
--     trial_plan_expiry_date,
--     depth,
--     approved,
--     tree_key,
--     record_date,
--     billing_status,
--     dmarc_management,
--     dmarc_domains_number,
--     null as dmarc_ironscales_plan,
--     null as dmarc_ironscales_plan_name
-- from PROD_CONFORM.DBT_PROD_DB.global_tenant_history_daily_agg_billing_tbl

-- union 

select
    date_recorded,
    root,
    parent_global_id,
    parent_name,
    tenant_global_id,
    tenant_name,
    registration_date,
    domain,
    partner_pricing,
    plan_id,
    plan_name,
    premium_id,
    premium_name,
    incident_management,
    security_awareness_training,
    simulation_and_training_bundle,
    simulation_and_training_bundle_plus,
    ai_empower_bundle,
    themis_co_pilot,
    ato,
    teams_protection,
    file_scanning,
    link_scanning,
    multi_tenancy,
    licensed_profiles,
    active_profiles,
    shared_profiles,
    trial_plan_id,
    trial_plan_name,
    trial_premium_id,
    trial_premium_name,
    trial_plan_expiry_date,
    depth,
    approved,
    tree_key,
    record_date,
    billing_status,
    dmarc_management,
    dmarc_domains_number,
    dmarc_ironscales_plan,
    dmarc_ironscales_plan_name
from global_tenant_history_daily_billing_tbl