models:
  - name: global_tenant_history
    config:
      grants:
        select: ['RIVERY_ROLE']

  - name: ltp_daily_itemized_billing_tbl
    config:
      grants:
        select: ['RIVERY_ROLE']
 
  - name: ltp_monthly_itemized_billing_tbl
    config:
      grants:
        select: ['RIVERY_ROLE']

  - name: daily_billable_mailbox_tbl
    config:
      grants:
        select: ['RIVERY_ROLE_UPDATED']

  - name: monthly_billable_mailbox_tbl
    config:
      grants:
        select: ['RIVERY_ROLE_UPDATED']